'use strict';
//This is a DOM element, Selecting elements 
const player0 = document.querySelector('.player--0');
const player1 = document.querySelector('.player--1');
const score0El = document.querySelector('#score--0');
const current0 = document.getElementById('current--0'); //This method is faster then querySelector
const score1EL = document.getElementById('score--1');
const current1 = document.getElementById('current--1');
const diceEl = document.querySelector('.dice');
const btnNew = document.querySelector('.btn--new');
const btnRoll = document.querySelector('.btn--roll');
const btnHold = document.querySelector('.btn--hold');

//Declaring the following as empty variables 
let scores, currentScore, activePlayer, playing;

//starting conditions
const init = function() {
    scores = [0, 0];
    currentScore = 0;
    activePlayer = 0;
    playing = true;
    score0El.textContent = 0;
    score1EL.textContent = 0;
    current0.textContent = 0;
    current1.textContent = 0;
    diceEl.classList.add('hidden');
    diceEl.classList.add('hidden');
    player0.classList.remove('player--winner');
    player1.classList.remove('player--winner');
    player0.classList.add('player--active');
    player1.classList.remove('player--active');

};
init();
//Switching between player 1 and player 2
const switchPlayer = function() {
    activePlayer = activePlayer === 0 ? 1 : 0;
    currentScore = 0;
    document.getElementById(`current--${activePlayer}`).textContent = 0;
    player0.classList.toggle('player--active');
    player1.classList.toggle('player--active');
};

//Implementing rolling dice funtionality
btnRoll.addEventListener('click', function() {
    if (playing) {
        //1.Genrating a random dice roll
        const dice = Math.trunc(Math.random() * 6) + 1;
        //2.Display dice 
        diceEl.classList.remove('hidden');
        diceEl.src = `dice-${dice}.png`; //This dynamically ensures that the correct img is displayed based on the number   generated by the math.random
        //3.check for 1
        if (dice !== 1) {
            currentScore += dice; //add dice amount to current score 
            document.getElementById(`current--${activePlayer}`).textContent = currentScore;
        } else {
            switchPlayer();
            //calling the switchPlayer function
        }
    }
});
//Hold button
btnHold.addEventListener('click', function() {
    if (playing) {
        //1.Add currentscore to active player
        scores[activePlayer] += currentScore;
        document.getElementById(`score--${activePlayer}`).textContent = scores[activePlayer]; //This adds the current score to the current active player
        //2.check if score is >=100
        if (scores[activePlayer] >= 20) {
            //finish game
            playing = false;
            diceEl.classList.add('hidden');
            document.querySelector(`.player--${activePlayer}`).classList.add('player--winner');
            document.querySelector(`.player--${activePlayer}`).classList.remove('player--active');
        } else {
            switchPlayer();
        }
    }
});
//New Game
btnNew.addEventListener('click', init);